on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          swift test
