on: pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild clean test -project AVFoundation-Combine.xcodeproj -scheme AVFoundation-Combine -destination platform=iOS Simulator,name=iPhone 11 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
